#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.

# Color variables for output messages
red='\e[0;31m'
green='\e[0;32m'
yellow='\e[0;33m'
clear='\e[0m'

echo -e "${yellow}🔍 Running ESLint...${clear}"
if ! npx eslint . --fix; then
    echo -e "${red}❌ ESLint checks failed. Please fix the issues before committing.${clear}"
    exit 1
fi

echo -e "${yellow}📝 Running Prettier...${clear}"
if ! npx prettier --write .; then
    echo -e "${red}❌ Prettier formatting issues found. Please format your code before committing.${clear}"
    exit 1
fi

echo -e "${yellow}🔍 Running TypeScript checks...${clear}"
if ! npx tsc --noEmit -p ./client/tsconfig.json; then
    echo -e "${red}❌ TypeScript checks failed in client. Please fix the errors before committing.${clear}"
    exit 1
fi

if ! npx tsc --noEmit -p ./server/tsconfig.json; then
    echo -e "${red}❌ TypeScript checks failed in server. Please fix the errors before committing.${clear}"
    exit 1
fi


echo -e "${yellow}🧪 Running tests...${clear}"
if ! npm test; then
    echo -e "${red}❌ Tests failed. Please fix the errors before committing.${clear}"
    exit 1
fi

echo -e "${yellow}🔒 Running npm audit...${clear}"
if ! npm audit --exit-code; then
    echo -e "${red}❌ Security vulnerabilities found. Please fix them before committing.${clear}"
    exit 1
fi

echo -e "${yellow}🚫 Checking for large files...${clear}"
for file in $(git diff --cached --name-only); do
    if [ $(wc -c < "$file") -gt 1048576 ]; then
        echo -e "${red}❌ File $file is larger than 1MB. Please remove it from your commit.${clear}"
        exit 1
    fi
done

echo -e "${green}✅ All checks passed! Ready to commit.${clear}"
